apps/accounts/urls.py
"""
URLCONF for the user accounts app (part 1/2).
"""

from django.conf.urls import url

from . import views


# User accounts URL patterns configuration
urlpatterns = (

    # Accounts list index page
    url(r'^$', views.accounts_list, name='index'),

    # Public user profile
    url(r'^(?P<username>[\w.@+-]+)/$', views.public_account_show, name="user_profile"),
)

apps/blog/urls.py
"""
URLCONF for the blog app.
"""

from django.conf.urls import url

from . import views, feeds


# URL patterns configuration
urlpatterns = (

    # Blog index page
    url(r'^$', views.article_list, name='index'),

    # Latest articles feed
    url(r'^flux/$', feeds.LatestArticlesFeed(), name='latest_articles_rss'),
    url(r'^flux/atom/$', feeds.LatestArticlesAtomFeed(), name='latest_articles_atom'),

    # Article tag index view
    url(r'^tags/$', views.tag_list, name='tag_list'),

    # Latest articles for a specific tag feed
    url(r'^tags/(?P<slug>[-a-zA-Z0-9_]+)/flux/$', feeds.LatestArticlesForTagFeed(),
        name='latest_tag_articles_rss'),
    url(r'^tags/(?P<slug>[-a-zA-Z0-9_]+)/flux/atom/$', feeds.LatestArticlesForTagAtomFeed(),
        name='latest_tag_articles_atom'),

    # Article tag view
    url(r'^tags/(?P<slug>[-a-zA-Z0-9_]+)/$', views.tag_detail, name='tag_detail'),

    # Article category index view
    url(r'^categories/$', views.category_list, name='category_list'),

    # Latest articles for a specific category feed
    url(r'^categories/(?P<hierarchy>[-a-zA-Z0-9_/]+)/flux/$', feeds.LatestArticlesForCategoryFeed(),
        name='latest_category_articles_rss'),
    url(r'^categories/(?P<hierarchy>[-a-zA-Z0-9_/]+)/flux/atom/$', feeds.LatestArticlesForCategoryAtomFeed(),
        name='latest_category_articles_atom'),

    # Article category view
    url(r'^categories/(?P<hierarchy>[-a-zA-Z0-9_/]+)/$', views.category_detail, name='category_detail'),

    # Article archives views
    url(r'^archives/$', views.archive_index, name='archive_index'),
    url(r'^archives/(?P<year>[0-9]{4})/$', views.archive_year, name='archive_year'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.archive_month, name='archive_month'),

    # Archives feed
    url(r'^archives/(?P<year>[0-9]{4})/flux/$', feeds.ArticlesForYearFeed(),
        name='articles_archive_year_rss'),
    url(r'^archives/(?P<year>[0-9]{4})/flux/atom/$', feeds.ArticlesForYearAtomFeed(),
        name='articles_archive_year_atom'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/flux/$', feeds.ArticlesForYearAndMonthFeed(),
        name='articles_archive_month_rss'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/flux/atom/$', feeds.ArticlesForYearAndMonthAtomFeed(),
        name='articles_archive_month_atom'),

    # Article detail views
    url(r'^(?P<year>[0-9]{4})/(?P<slug>[-a-zA-Z0-9_]+)/$',
        views.article_detail_year_month_day, name='article_detail_year'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<slug>[-a-zA-Z0-9_]+)/$',
        views.article_detail_year_month_day, name='article_detail_year_month'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/(?P<slug>[-a-zA-Z0-9_]+)/$',
        views.article_detail_year_month_day, name='article_detail_year_month_day'),
    url(r'^(?P<slug>[-a-zA-Z0-9_]+)/$', views.article_detail, name='article_detail'),
)

apps/changemail/urls.py
"""
URLCONF for the change email app.
"""

from django.conf.urls import url

from . import views


# URL patterns configuration
urlpatterns = (

    # Step 1: request email change
    url(r'^$', views.change_email, {
        'post_change_redirect': 'myaccountmail:email_change_done',
        'email_template_name': 'changemail/email_change_email.txt',
        'html_email_template_name': 'changemail/email_change_email.html',
        'subject_template_name': 'changemail/email_change_subject.txt'
    }, name='email_change'),

    # Step 2: confirmation link sent
    url(r'^ok/$', views.change_email_done, name='email_change_done'),

    # Step 3 confirm request
    url(r'^confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<addressb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.change_email_confirm, {
            'post_confirm_redirect': 'myaccountmail:email_change_complete'
        },
        name='email_change_confirm'),

    # Step 4: Email changed
    url(r'^fait/$', views.change_email_complete, name='email_change_complete'),
)

apps/forum/urls.py
"""
URLCONF for the forum app.
"""

from django.conf.urls import url
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from apps.contentreport.views import report_content

from . import views, feeds
from .models import ForumThreadPost
from .forms import ForumThreadPostReportForm


# URL patterns configuration
urlpatterns = (

    # Forum index page
    url(r'^$', views.forum_index, name='index'),
    url(r'^topics/$', RedirectView.as_view(url=reverse_lazy('forum:index'), permanent=True)),
    url(r'^posts/$', RedirectView.as_view(url=reverse_lazy('forum:index'), permanent=True)),

    # Forum's thread detail view
    url(r'^topics/(?P<pk>[0-9]+)-(?P<slug>[\w-]+)/$', views.forum_thread_show, name='thread_detail'),

    # Forum's thread edit view
    url(r'^topics/(?P<pk>[0-9]+)-(?P<slug>[\w-]+)/modifier/$', views.forum_thread_edit, name='thread_edit'),

    # Forum's thread delete view
    url(r'^topics/(?P<pk>[0-9]+)-(?P<slug>[\w-]+)/supprimer/$', views.forum_thread_delete, name='thread_delete'),

    # Forum's thread delete view
    url(r'^topics/(?P<pk>[0-9]+)-(?P<slug>[\w-]+)/repondre/$', views.forum_thread_reply, name='thread_reply'),

    # Issue ticket subscription management
    url(r'^topics/(?P<pk>[0-9]+)-(?P<slug>[\w-]+)/abonner/$', views.topic_subscribe, name='thread_subscribe'),
    url(r'^topics/(?P<pk>[0-9]+)-(?P<slug>[\w-]+)/desabonner/$', views.topic_unsubscribe, name='thread_unsubscribe'),

    # Latest forum's threads feeds
    url(r'^topics/flux/$', feeds.LatestForumThreadsFeed(),
        name='latest_forum_threads_rss'),
    url(r'^topics/flux/atom/$', feeds.LatestForumThreadsAtomFeed(),
        name='latest_forum_threads_atom'),

    # Latest forum's thread's posts for a given thread feeds
    url(r'^topics/(?P<pk>\d+)-(?P<slug>[\w-]+)/flux/$', feeds.LatestForumPostsForThreadFeed(),
        name='latest_forum_thread_posts_for_thread_rss'),
    url(r'^topics/(?P<pk>\d+)-(?P<slug>[\w-]+)/flux/atom/$', feeds.LatestForumPostsForThreadAtomFeed(),
        name='latest_forum_thread_posts_for_thread_atom'),

    # Forum's thread's post detail view (redirect to thread view)
    url(r'^posts/(?P<pk>[0-9]+)/$', views.forum_thread_post_show, name='post_detail'),

    # Forum's thread's post edit view
    url(r'^posts/(?P<pk>[0-9]+)/modifier/$', views.forum_thread_post_edit, name='post_edit'),

    # Forum's thread's post delete view
    url(r'^posts/(?P<pk>[0-9]+)/supprimer/$', views.forum_thread_post_delete, name='post_delete'),

    # Forum's thread's post reply (with quote) view
    url(r'^posts/(?P<pk>[0-9]+)/repondre/$', views.forum_thread_post_reply, name='post_reply'),

    # Forum's thread's post report view
    url(r'^posts/(?P<pk>[0-9]+)/signaler/$', report_content, kwargs={
        'objects_loader': ForumThreadPost.objects.published().select_related('parent_thread',
                                                                             'parent_thread__parent_forum',
                                                                             'author'),
        'content_object_name': 'post',
        'template_name': 'forum/forum_thread_post_report.html',
        'content_report_form': ForumThreadPostReportForm,
    }, name='post_report'),

    # Latest forum's thread's posts feeds
    url(r'^posts/flux/$', feeds.LatestForumPostsFeed(),
        name='latest_forum_thread_posts_rss'),
    url(r'^posts/flux/atom/$', feeds.LatestForumPostsAtomFeed(),
        name='latest_forum_thread_posts_atom'),

    # My account view
    url(r'^mon-compte/$', views.my_account_show, name='myaccount'),

    # My threads and posts list view
    url(r'^mon-compte/mes-topics/$', views.my_threads_list, name='mythreads_list'),
    url(r'^mon-compte/mes-posts/$', views.my_posts_list, name='myposts_list'),

    # My forum's subscriptions list view
    url(r'^mon-compte/mes-abonnements-forums/$', views.my_forums_subscription_list, name='myforumsubscribtions_list'),
    url(r'^mon-compte/mes-abonnements-topics/$', views.my_threads_subscription_list, name='mythreadsubscribtions_list'),

    # Forum's thread create view
    url(r'^(?P<hierarchy>[\w/-]+)/nouveau-topic/$', views.forum_thread_create, name='thread_create'),

    # Issue ticket subscription management
    url(r'^(?P<hierarchy>[\w/-]+)/abonner/$', views.forum_subscribe, name='forum_subscribe'),
    url(r'^(?P<hierarchy>[\w/-]+)/desabonner/$', views.forum_unsubscribe, name='forum_unsubscribe'),

    # Latest forum's threads for a given forum feeds
    url(r'^(?P<hierarchy>[\w/-]+)/flux-topics/$', feeds.LatestForumThreadsForForumFeed(),
        name='latest_forum_threads_for_forum_rss'),
    url(r'^(?P<hierarchy>[\w/-]+)/flux-topics/atom/$', feeds.LatestForumThreadsForForumAtomFeed(),
        name='latest_forum_threads_for_forum_atom'),

    # Latest forum's thread's posts for a given forum feeds
    url(r'^(?P<hierarchy>[\w/-]+)/flux-posts/$', feeds.LatestForumPostsForForumFeed(),
        name='latest_forum_thread_posts_for_forum_rss'),
    url(r'^(?P<hierarchy>[\w/-]+)/flux-posts/atom/$', feeds.LatestForumPostsForForumAtomFeed(),
        name='latest_forum_thread_posts_for_forum_atom'),

    # Mark all threads of the forum as read confirm view
    url(r'^(?P<hierarchy>[\w/-]+)/menage/$', views.forum_mark_all_thread_as_read,
        name='forum_mark_all_threads_as_read'),

    # Sub-forum detail view
    # NOTE: Always last URL because regex match nearly every possible urls.
    url(r'^(?P<hierarchy>[\w/-]+)/$', views.forum_show, name='forum_detail'),
)

apps/staticpages/urls.py
"""
URLCONF for the static pages app.
"""

from django.conf.urls import url

from . import views


# URL patterns configuration
urlpatterns = (

    # Index page
    url(r'^$', views.index_page, name='index'),

    # All static pages
    url(r'^pourquoi-ce-site/$', views.why_this_site, name='why_this_site'),
    url(r'^qui-sommes-nous/$', views.about_us, name='about_us'),
    url(r'^nous-contacter/$', views.contact_us, name='contact_us'),
    url(r'^cookies/$', views.cookies_usage, name='cookies_usage'),
    url(r'^mentions-legales/$', views.legal_notices, name='legal_notices'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^nos-engagements/$', views.our_commitments, name='our_commitments'),
    url(r'^plan-du-site/$', views.human_sitemap, name='human_sitemap'),
    url(r'^conditions-generales-d-utilisation/$', views.tos, name='tos'),
)

carnetdumaker/urls.py
"""
Root URLCONF for the CarnetDuMaker project.
"""

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.sitemaps import views as sitemaps_views

from apps.accounts.sitemap import AccountsSitemap
from apps.announcements.sitemap import (AnnouncementsSitemap,
                                        AnnouncementTagsSitemap)
from apps.blog.sitemap import (ArticlesSitemap,
                               ArticleTagsSitemap,
                               ArticleCategoriesSitemap)
from apps.bugtracker.sitemap import IssueTicketsSitemap
from apps.forum.sitemap import (ForumsSitemap,
                                ForumThreadsSitemap)
from apps.imageattachments.sitemap import ImageAttachmentsSitemap
from apps.licenses.sitemap import LicensesSitemap
from apps.snippets.sitemap import CodeSnippetsSitemap
from apps.staticpages.sitemap import StaticPagesSitemap


# Patch admin site
admin.site.site_title = 'TamiaLab admin'
admin.site.site_header = 'TamiaLab administration'


# Root URL patterns configuration
urlpatterns = patterns('',

    # Home page
    url(r'^', include('apps.home.urls', namespace='home')),

    # Search engine
    url(r'^recherche/', include('haystack.urls', namespace='search')),

    # Blog / Forum / Boutique
    url(r'^articles/', include('apps.blog.urls', namespace='blog')),
    url(r'^forum/', include('apps.forum.urls', namespace='forum')),
    url(r'^boutique/', include('apps.shop.urls', namespace='shop')),

    # Paid membership and billing
    # TODO url(r'^abonnements/', include('apps.membership.urls', namespace='membership')),
    # TODO url(r'^factures/', include('apps.billing.urls', namespace='billing')),

    # Image attachments
    url(r'^images/', include('apps.imageattachments.urls', namespace='imageattachments')),

    # User public profiles
    url(r'^membres/', include('apps.accounts.urls', namespace='accounts')),

    # My account
    url(r'^mon-compte/', include('apps.accounts.myaccount_urls', namespace='myaccount')),
    url(r'^mon-compte/modification-adresse-email/', include('apps.changemail.urls', namespace='myaccountmail')),

    # Log watcher account history
    url(r'^mon-compte/historique-connexion/', include('apps.loginwatcher.urls', namespace='loginwatcher')),

    # API key manager
    url(r'^mon-compte/clef-api/', include('apps.userapikey.urls', namespace='userapikey')),

    # User login and registration
    url(r'^authentification/', include('apps.registration.auth_urls', namespace='auth')),
    url(r'^inscription/', include('apps.registration.urls', namespace='registration')),

    # Notifications
    url(r'^notifications/', include('apps.notifications.urls', namespace='notifications')),

    # Private messages
    url(r'^messages/', include('apps.privatemsg.urls', namespace='privatemsg')),

    # Bug tracker
    url(r'^bugtracker/', include('apps.bugtracker.urls', namespace='bugtracker')),

    # Announcements
    url(r'^annonces/', include('apps.announcements.urls', namespace='announcements')),

    # code snippets
    url(r'^snippets/', include('apps.snippets.urls', namespace='snippets')),

    # User badges
    # TODO url(r'^badges/', include('apps.badges.urls', namespace='badges')),

    # Static pages
    url(r'^pages/', include('apps.staticpages.urls', namespace='staticpages')),

    # Content licenses
    url(r'^licences/', include('apps.licenses.urls', namespace='licenses')),
    url(r'^licences/', include('apps.blog.license_urls', namespace='bloglicense')),

    # Content report pages
    url(r'^signalement/', include('apps.contentreport.urls', namespace='contentreport')),

    # Text rendering preview
    url(r'^api/texte/', include('apps.txtrender.urls', namespace='txtrender')),

    # Instant Payment Notification callback hook listener(s)
    # TODO url(r'^api/ipn/', include('apps.payments.urls', namespace='payments')),

    # Admin pages
    url(r'^admin/', include(admin.site.urls)),
)

# Sitemap index and section
sitemaps = {
    'accounts': AccountsSitemap,
    'announcements': AnnouncementsSitemap,
    'announcement_tas': AnnouncementTagsSitemap,
    'blog_articles': ArticlesSitemap,
    'blog_tags': ArticleTagsSitemap,
    'blog_categories': ArticleCategoriesSitemap,
    'bugtracker': IssueTicketsSitemap,
    'forum_forums': ForumsSitemap,
    'forum_threads': ForumThreadsSitemap,
    'imageattachments': ImageAttachmentsSitemap,
    'licenses': LicensesSitemap,
    'snippets': CodeSnippetsSitemap,
    'staticpages': StaticPagesSitemap,
}
urlpatterns += patterns('',
    (r'^sitemap\.xml$', sitemaps_views.index, {'sitemaps': sitemaps}),
    (r'^sitemap-(?P<section>.+)\.xml$', sitemaps_views.sitemap, {'sitemaps': sitemaps}),
)

# Static/media files serving for debug ONLY, static() do nothing when DEBUG=False
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

templates/changemail/email_change_complete.html
{% extends "accounts/base_myaccount.html" %}
{% load bootstrapform %}

{% block breadcrumb %}{{ block.super }}
    <li><a href="{% url 'myaccountmail:email_change_complete' %}">Modification d'adresse email terminée</a></li>{% endblock %}

{% block content %}

    <!-- Change email form -->
    <div class="col-md-12">

        <!-- Return link -->
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h1 class="panel-title"><i class="fa fa-envelope"></i> Modification d'adresse email terminée</h1>
            </div>

            <div class="panel-body">
                <p>Votre adresse email a été modifié avec succés. Vous receverez désormais vos emails sur votre nouvelle adresse.</p>
            </div>
        </div>

        <!-- Return link -->
        <p><a href="{% url 'myaccount:index' %}"><i class="fa fa-arrow-left"></i> Retour aux informations du compte</a></p>
    </div>
{% endblock %}

templates/changemail/email_change_confirm_failed.html
{% extends "accounts/base_myaccount.html" %}

{% block breadcrumb %}{{ block.super }}
    <li><a href="#">Modification de l'adresse email impossible</a></li>{% endblock %}

{% block content %}

    <!-- Email modification failed -->
    <div class="col-md-12">

        <!-- Error message -->
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h1 class="panel-title"><i class="fa fa-envelope"></i> Modification de l'adresse email impossible</h1>
            </div>

            <div class="panel-body">
                <p>Votre adresse email n'a pas pu être modifiée car le lien de confirmation est incorrect ou a expiré.</p>
                <p>Vérifiez que le lien est correct (erreur de copier coller par exemple), ou à défaut, recommencez le processus de modification.</p>
                <p>En cas de probléme, n'hésitez pas à <a href="{% url 'staticpages:contact_us' %}">contacter l'administrateur du site</a>.</p>
            </div>
        </div>

        <!-- Return link -->
        <p><a href="{% url 'myaccount:index' %}"><i class="fa fa-arrow-left"></i> Retour aux informations du compte</a></p>
    </div>
{% endblock %}

templates/changemail/email_change_done.html
{% extends "accounts/base_myaccount.html" %}
{% load bootstrapform %}

{% block breadcrumb %}{{ block.super }}
    <li><a href="{% url 'myaccountmail:email_change_done' %}">Demande de modification d'adresse email enregistrée</a></li>{% endblock %}

{% block content %}

    <!-- Email modification registered -->
    <div class="col-md-12">

        <!-- Confirmation message -->
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h1 class="panel-title"><i class="fa fa-envelope"></i> Demande de modification d'adresse email enregistrée</h1>
            </div>

            <div class="panel-body">
                <p>Un mail vous a été envoyé avec un lien permettant de valider la modification de votre adresse email.</p>
                <p>Veuillez vérifier votre boite mail.</p>
                <p>Remarque : le mail peut mettre quelques minutes avant d'apparaitre dans votre boite mail.</p>
            </div>
        </div>

        <!-- Return link -->
        <p><a href="{% url 'myaccount:index' %}"><i class="fa fa-arrow-left"></i> Retour aux informations du compte</a></p>
    </div>
{% endblock %}

templates/changemail/email_change_email.html
<!DOCTYPE html>
<html>
    <head lang="fr">
        <meta charset="UTF-8">
        <title>Confirmation de changement d'adresse email | {{ site_name }}</title>
    </head>
    <body>
        <p>Bonjour {{ user.username }},</p>

        <p>Une demande de changement d'adresse email sur {{ site_name }} a été effectuée via votre adresse mail {{ email }}.</p>

        <p>Si vous êtes à l'origine de cette demande, merci de cliquer sur le lien ci-dessous pour finaliser la modification :</p>
        <a href="{{ protocol }}://{{ domain }}{% url 'myaccountmail:email_change_confirm' uidb64=uid token=token addressb64=addressb64 %}">Modifier mon adresse email sur {{ site_name }}</a>

        <p>Attention : le lien ci-dessus n'est valable que pendant {{ confirmation_timeout_days }} jours.</p>

        <p>Si vous n'êtes pas à l'origine de cette demande, vous pouvez tout simplement ignorer ce mail.</p>

        <p>Cordialement,</p>
        <p>L'équipe de {{ site_name }}</p>

        {% include "email_legal_footer.html" %}
    </body>
</html>

templates/changemail/email_change_form.html
{% extends "accounts/base_myaccount.html" %}
{% load bootstrapform %}

{% block breadcrumb %}{{ block.super }}
    <li><a href="{% url 'myaccountmail:email_change' %}">Modification de l'adresse email</a></li>{% endblock %}

{% block title %}Modification de l'adresse email | {{ block.super }}{% endblock %}

{% block content %}

    <!-- Change email form -->
    <div class="col-md-12">

        <!-- Change email form panel -->
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h1 class="panel-title"><i class="fa fa-envelope"></i> Modification de l'adresse email</h1>
            </div>

            <div class="panel-body">
                <form method="post" action="{% url 'myaccountmail:email_change' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="control-label">Adresse actuelle</label>
                        <p class="form-control-static">{{ user.email }}</p>
                    </div>
                    {{ form|bootstrapform }}
                    <input type="submit" class="btn btn-primary center-block" value="Modifier l'adresse email" />
                </form>
            </div>
        </div>

        <!-- Return link -->
        <p><a href="{% url 'myaccount:index' %}"><i class="fa fa-arrow-left"></i> Retour aux informations du compte</a></p>
    </div>
{% endblock %}