apps/accounts/urls.py
"""
URLCONF for the user accounts app (part 1/2).
"""

from django.conf.urls import url

from . import views


# User accounts URL patterns configuration
urlpatterns = (

    # Accounts list index page
    url(r'^$', views.accounts_list, name='index'),

    # Public user profile
    url(r'^(?P<username>[\w.@+-]+)/$', views.public_account_show, name="user_profile"),
)

apps/blog/urls.py
"""
URLCONF for the blog app.
"""

from django.conf.urls import url

from . import views, feeds


# URL patterns configuration
urlpatterns = (

    # Blog index page
    url(r'^$', views.article_list, name='index'),

    # Latest articles feed
    url(r'^flux/$', feeds.LatestArticlesFeed(), name='latest_articles_rss'),
    url(r'^flux/atom/$', feeds.LatestArticlesAtomFeed(), name='latest_articles_atom'),

    # Article tag index view
    url(r'^tags/$', views.tag_list, name='tag_list'),

    # Latest articles for a specific tag feed
    url(r'^tags/(?P<slug>[-a-zA-Z0-9_]+)/flux/$', feeds.LatestArticlesForTagFeed(),
        name='latest_tag_articles_rss'),
    url(r'^tags/(?P<slug>[-a-zA-Z0-9_]+)/flux/atom/$', feeds.LatestArticlesForTagAtomFeed(),
        name='latest_tag_articles_atom'),

    # Article tag view
    url(r'^tags/(?P<slug>[-a-zA-Z0-9_]+)/$', views.tag_detail, name='tag_detail'),

    # Article category index view
    url(r'^categories/$', views.category_list, name='category_list'),

    # Latest articles for a specific category feed
    url(r'^categories/(?P<hierarchy>[-a-zA-Z0-9_/]+)/flux/$', feeds.LatestArticlesForCategoryFeed(),
        name='latest_category_articles_rss'),
    url(r'^categories/(?P<hierarchy>[-a-zA-Z0-9_/]+)/flux/atom/$', feeds.LatestArticlesForCategoryAtomFeed(),
        name='latest_category_articles_atom'),

    # Article category view
    url(r'^categories/(?P<hierarchy>[-a-zA-Z0-9_/]+)/$', views.category_detail, name='category_detail'),

    # Article archives views
    url(r'^archives/$', views.archive_index, name='archive_index'),
    url(r'^archives/(?P<year>[0-9]{4})/$', views.archive_year, name='archive_year'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.archive_month, name='archive_month'),

    # Archives feed
    url(r'^archives/(?P<year>[0-9]{4})/flux/$', feeds.ArticlesForYearFeed(),
        name='articles_archive_year_rss'),
    url(r'^archives/(?P<year>[0-9]{4})/flux/atom/$', feeds.ArticlesForYearAtomFeed(),
        name='articles_archive_year_atom'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/flux/$', feeds.ArticlesForYearAndMonthFeed(),
        name='articles_archive_month_rss'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/flux/atom/$', feeds.ArticlesForYearAndMonthAtomFeed(),
        name='articles_archive_month_atom'),

    # Article detail views
    url(r'^(?P<year>[0-9]{4})/(?P<slug>[-a-zA-Z0-9_]+)/$',
        views.article_detail_year_month_day, name='article_detail_year'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<slug>[-a-zA-Z0-9_]+)/$',
        views.article_detail_year_month_day, name='article_detail_year_month'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/(?P<slug>[-a-zA-Z0-9_]+)/$',
        views.article_detail_year_month_day, name='article_detail_year_month_day'),
    url(r'^(?P<slug>[-a-zA-Z0-9_]+)/$', views.article_detail, name='article_detail'),
)

apps/forum/urls.py
"""
URLCONF for the forum app.
"""

from django.conf.urls import url
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from apps.contentreport.views import report_content

from . import views, feeds
from .models import ForumThreadPost
from .forms import ForumThreadPostReportForm


# URL patterns configuration
urlpatterns = (

    # Forum index page
    url(r'^$', views.forum_index, name='index'),
    url(r'^topics/$', RedirectView.as_view(url=reverse_lazy('forum:index'), permanent=True)),
    url(r'^posts/$', RedirectView.as_view(url=reverse_lazy('forum:index'), permanent=True)),

    # Forum's thread detail view
    url(r'^topics/(?P<pk>[0-9]+)-(?P<slug>[\w-]+)/$', views.forum_thread_show, name='thread_detail'),

    # Forum's thread edit view
    url(r'^topics/(?P<pk>[0-9]+)-(?P<slug>[\w-]+)/modifier/$', views.forum_thread_edit, name='thread_edit'),

    # Forum's thread delete view
    url(r'^topics/(?P<pk>[0-9]+)-(?P<slug>[\w-]+)/supprimer/$', views.forum_thread_delete, name='thread_delete'),

    # Forum's thread delete view
    url(r'^topics/(?P<pk>[0-9]+)-(?P<slug>[\w-]+)/repondre/$', views.forum_thread_reply, name='thread_reply'),

    # Issue ticket subscription management
    url(r'^topics/(?P<pk>[0-9]+)-(?P<slug>[\w-]+)/abonner/$', views.topic_subscribe, name='thread_subscribe'),
    url(r'^topics/(?P<pk>[0-9]+)-(?P<slug>[\w-]+)/desabonner/$', views.topic_unsubscribe, name='thread_unsubscribe'),

    # Latest forum's threads feeds
    url(r'^topics/flux/$', feeds.LatestForumThreadsFeed(),
        name='latest_forum_threads_rss'),
    url(r'^topics/flux/atom/$', feeds.LatestForumThreadsAtomFeed(),
        name='latest_forum_threads_atom'),

    # Latest forum's thread's posts for a given thread feeds
    url(r'^topics/(?P<pk>\d+)-(?P<slug>[\w-]+)/flux/$', feeds.LatestForumPostsForThreadFeed(),
        name='latest_forum_thread_posts_for_thread_rss'),
    url(r'^topics/(?P<pk>\d+)-(?P<slug>[\w-]+)/flux/atom/$', feeds.LatestForumPostsForThreadAtomFeed(),
        name='latest_forum_thread_posts_for_thread_atom'),

    # Forum's thread's post detail view (redirect to thread view)
    url(r'^posts/(?P<pk>[0-9]+)/$', views.forum_thread_post_show, name='post_detail'),

    # Forum's thread's post edit view
    url(r'^posts/(?P<pk>[0-9]+)/modifier/$', views.forum_thread_post_edit, name='post_edit'),

    # Forum's thread's post delete view
    url(r'^posts/(?P<pk>[0-9]+)/supprimer/$', views.forum_thread_post_delete, name='post_delete'),

    # Forum's thread's post reply (with quote) view
    url(r'^posts/(?P<pk>[0-9]+)/repondre/$', views.forum_thread_post_reply, name='post_reply'),

    # Forum's thread's post report view
    url(r'^posts/(?P<pk>[0-9]+)/signaler/$', report_content, kwargs={
        'objects_loader': ForumThreadPost.objects.published().select_related('parent_thread',
                                                                             'parent_thread__parent_forum',
                                                                             'author'),
        'content_object_name': 'post',
        'template_name': 'forum/forum_thread_post_report.html',
        'content_report_form': ForumThreadPostReportForm,
    }, name='post_report'),

    # Latest forum's thread's posts feeds
    url(r'^posts/flux/$', feeds.LatestForumPostsFeed(),
        name='latest_forum_thread_posts_rss'),
    url(r'^posts/flux/atom/$', feeds.LatestForumPostsAtomFeed(),
        name='latest_forum_thread_posts_atom'),

    # My account view
    url(r'^mon-compte/$', views.my_account_show, name='myaccount'),

    # My threads and posts list view
    url(r'^mon-compte/mes-topics/$', views.my_threads_list, name='mythreads_list'),
    url(r'^mon-compte/mes-posts/$', views.my_posts_list, name='myposts_list'),

    # My forum's subscriptions list view
    url(r'^mon-compte/mes-abonnements-forums/$', views.my_forums_subscription_list, name='myforumsubscribtions_list'),
    url(r'^mon-compte/mes-abonnements-topics/$', views.my_threads_subscription_list, name='mythreadsubscribtions_list'),

    # Forum's thread create view
    url(r'^(?P<hierarchy>[\w/-]+)/nouveau-topic/$', views.forum_thread_create, name='thread_create'),

    # Issue ticket subscription management
    url(r'^(?P<hierarchy>[\w/-]+)/abonner/$', views.forum_subscribe, name='forum_subscribe'),
    url(r'^(?P<hierarchy>[\w/-]+)/desabonner/$', views.forum_unsubscribe, name='forum_unsubscribe'),

    # Latest forum's threads for a given forum feeds
    url(r'^(?P<hierarchy>[\w/-]+)/flux-topics/$', feeds.LatestForumThreadsForForumFeed(),
        name='latest_forum_threads_for_forum_rss'),
    url(r'^(?P<hierarchy>[\w/-]+)/flux-topics/atom/$', feeds.LatestForumThreadsForForumAtomFeed(),
        name='latest_forum_threads_for_forum_atom'),

    # Latest forum's thread's posts for a given forum feeds
    url(r'^(?P<hierarchy>[\w/-]+)/flux-posts/$', feeds.LatestForumPostsForForumFeed(),
        name='latest_forum_thread_posts_for_forum_rss'),
    url(r'^(?P<hierarchy>[\w/-]+)/flux-posts/atom/$', feeds.LatestForumPostsForForumAtomFeed(),
        name='latest_forum_thread_posts_for_forum_atom'),

    # Mark all threads of the forum as read confirm view
    url(r'^(?P<hierarchy>[\w/-]+)/menage/$', views.forum_mark_all_thread_as_read,
        name='forum_mark_all_threads_as_read'),

    # Sub-forum detail view
    # NOTE: Always last URL because regex match nearly every possible urls.
    url(r'^(?P<hierarchy>[\w/-]+)/$', views.forum_show, name='forum_detail'),
)

apps/snippets/urls.py
"""
URLCONF for the code snippets app.
"""

from django.conf.urls import url

from . import views, feeds


# URL patterns configuration
urlpatterns = (

    # Snippets list view
    url(r'^$', views.snippet_list, name='index'),

    # RSS and ATOM feeds
    url(r'^flux/$', feeds.LatestCodeSnippetsFeed(), name='latest_snippets_rss'),
    url(r'^flux/atom/$', feeds.LatestCodeSnippetsAtomFeed(), name='latest_snippets_atom'),

    # Snippet detail page
    url(r'^(?P<pk>[0-9]+)/$', views.snippet_detail, name='snippet_detail'),

    # Snippet raw content page
    url(r'^(?P<pk>[0-9]+)/source/$', views.snippet_raw, name='snippet_raw'),

    # Snippet download page
    url(r'^(?P<pk>[0-9]+)/telechargement/$', views.snippet_raw, {'download': True}, name='snippet_download'),

    # Snippet download in zip page
    url(r'^(?P<pk>[0-9]+)/telechargement-zip/$', views.snippet_zip_download, name='snippet_zip_download'),

    # Snippets bundle list view
    url(r'^dossiers/$', views.bundle_list, name='bundle_index'),

    # Snippets detail view
    url(r'^dossiers/(?P<pk>[0-9]+)/$', views.bundle_detail, name='bundle_detail'),

    # Snippet download page
    url(r'^dossiers/(?P<pk>[0-9]+)/telechargement/$', views.bundle_download, name='bundle_download'),
)

carnetdumaker/urls.py
"""
Root URLCONF for the CarnetDuMaker project.
"""

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.sitemaps import views as sitemaps_views

from apps.accounts.sitemap import AccountsSitemap
from apps.announcements.sitemap import (AnnouncementsSitemap,
                                        AnnouncementTagsSitemap)
from apps.blog.sitemap import (ArticlesSitemap,
                               ArticleTagsSitemap,
                               ArticleCategoriesSitemap)
from apps.bugtracker.sitemap import IssueTicketsSitemap
from apps.forum.sitemap import (ForumsSitemap,
                                ForumThreadsSitemap)
from apps.imageattachments.sitemap import ImageAttachmentsSitemap
from apps.licenses.sitemap import LicensesSitemap
from apps.snippets.sitemap import CodeSnippetsSitemap
from apps.staticpages.sitemap import StaticPagesSitemap


# Patch admin site
admin.site.site_title = 'TamiaLab admin'
admin.site.site_header = 'TamiaLab administration'


# Root URL patterns configuration
urlpatterns = patterns('',

    # Home page
    url(r'^', include('apps.home.urls', namespace='home')),

    # Search engine
    url(r'^recherche/', include('haystack.urls', namespace='search')),

    # Blog / Forum / Boutique
    url(r'^articles/', include('apps.blog.urls', namespace='blog')),
    url(r'^forum/', include('apps.forum.urls', namespace='forum')),
    url(r'^boutique/', include('apps.shop.urls', namespace='shop')),

    # Paid membership and billing
    # TODO url(r'^abonnements/', include('apps.membership.urls', namespace='membership')),
    # TODO url(r'^factures/', include('apps.billing.urls', namespace='billing')),

    # Image attachments
    url(r'^images/', include('apps.imageattachments.urls', namespace='imageattachments')),

    # User public profiles
    url(r'^membres/', include('apps.accounts.urls', namespace='accounts')),

    # My account
    url(r'^mon-compte/', include('apps.accounts.myaccount_urls', namespace='myaccount')),
    url(r'^mon-compte/modification-adresse-email/', include('apps.changemail.urls', namespace='myaccountmail')),

    # Log watcher account history
    url(r'^mon-compte/historique-connexion/', include('apps.loginwatcher.urls', namespace='loginwatcher')),

    # API key manager
    url(r'^mon-compte/clef-api/', include('apps.userapikey.urls', namespace='userapikey')),

    # User login and registration
    url(r'^authentification/', include('apps.registration.auth_urls', namespace='auth')),
    url(r'^inscription/', include('apps.registration.urls', namespace='registration')),

    # Notifications
    url(r'^notifications/', include('apps.notifications.urls', namespace='notifications')),

    # Private messages
    url(r'^messages/', include('apps.privatemsg.urls', namespace='privatemsg')),

    # Bug tracker
    url(r'^bugtracker/', include('apps.bugtracker.urls', namespace='bugtracker')),

    # Announcements
    url(r'^annonces/', include('apps.announcements.urls', namespace='announcements')),

    # code snippets
    url(r'^snippets/', include('apps.snippets.urls', namespace='snippets')),

    # User badges
    # TODO url(r'^badges/', include('apps.badges.urls', namespace='badges')),

    # Static pages
    url(r'^pages/', include('apps.staticpages.urls', namespace='staticpages')),

    # Content licenses
    url(r'^licences/', include('apps.licenses.urls', namespace='licenses')),
    url(r'^licences/', include('apps.blog.license_urls', namespace='bloglicense')),

    # Content report pages
    url(r'^signalement/', include('apps.contentreport.urls', namespace='contentreport')),

    # Text rendering preview
    url(r'^api/texte/', include('apps.txtrender.urls', namespace='txtrender')),

    # Instant Payment Notification callback hook listener(s)
    # TODO url(r'^api/ipn/', include('apps.payments.urls', namespace='payments')),

    # Admin pages
    url(r'^admin/', include(admin.site.urls)),
)

# Sitemap index and section
sitemaps = {
    'accounts': AccountsSitemap,
    'announcements': AnnouncementsSitemap,
    'announcement_tas': AnnouncementTagsSitemap,
    'blog_articles': ArticlesSitemap,
    'blog_tags': ArticleTagsSitemap,
    'blog_categories': ArticleCategoriesSitemap,
    'bugtracker': IssueTicketsSitemap,
    'forum_forums': ForumsSitemap,
    'forum_threads': ForumThreadsSitemap,
    'imageattachments': ImageAttachmentsSitemap,
    'licenses': LicensesSitemap,
    'snippets': CodeSnippetsSitemap,
    'staticpages': StaticPagesSitemap,
}
urlpatterns += patterns('',
    (r'^sitemap\.xml$', sitemaps_views.index, {'sitemaps': sitemaps}),
    (r'^sitemap-(?P<section>.+)\.xml$', sitemaps_views.sitemap, {'sitemaps': sitemaps}),
)

# Static/media files serving for debug ONLY, static() do nothing when DEBUG=False
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

templates/snippets/base_bundles.html
{% extends "snippets/base_snippets.html" %}

{% block breadcrumb %}{{ block.super }}
    <li><a href="{% url 'snippets:bundle_index' %}">Dossiers d'extraits de code</a></li>{% endblock %}

{% block feeds %}
    {# TODO Feeds #}
    <link rel="alternate" type="application/rss+xml" title="Extraits de code récentes (flux RSS)" href="{% url "snippets:latest_snippets_rss" %}">
    <link rel="alternate" type="application/atom+xml" title="Extraits de code récentes (flux Atom)" href="{% url "snippets:latest_snippets_atom" %}">
{% endblock %}

templates/snippets/base_snippets.html
{% extends "base_fullpage.html" %}

{% block breadcrumb %}{{ block.super }}
    <li><a href="{% url 'snippets:index' %}">Extraits de code</a></li>{% endblock %}

{% block feeds %}
    <link rel="alternate" type="application/rss+xml" title="Extraits de code récentes (flux RSS)" href="{% url "snippets:latest_snippets_rss" %}">
    <link rel="alternate" type="application/atom+xml" title="Extraits de code récentes (flux Atom)" href="{% url "snippets:latest_snippets_atom" %}">
{% endblock %}

templates/snippets/bundle_detail.html
{% extends "snippets/base_bundles.html" %}
{% load accounts tools %}

{% block breadcrumb %}{{ block.super }}
    <li><a href="{{ snippets_bundle.get_absolute_url }}">{{ snippets_bundle.title }}</a></li>{% endblock %}

{% block title %}{{ snippets_bundle.title }} | {{ block.super }}{% endblock %}

{% block opengraph_title %}{{ snippets_bundle.title }}{% endblock %}
{% block opengraph_description %}{{ snippets_bundle.description_text|truncatewords:200 }}{% endblock %}
{% block opengraph_image %}{% endblock %}
{% block opengraph_url %}{{ block.super }}{{ snippets_bundle.get_absolute_url }}{% endblock %}

{% block content %}

    <!-- Bundle detail -->
    <div class="col-md-12">

        <h1>{{ snippets_bundle.title }}</h1>

        <!-- Bundle information -->
        <p><i class="fa fa-user"></i> par {{ snippets_bundle.author|user_profile_link }} | <i class="fa fa-calendar"></i> {{ snippets_bundle.creation_date|datetime_html }}</p>
        {% if snippets_bundle.has_been_modified %}
            <p><i class="fa fa-edit"></i> Modifié pour la derniére fois le {{ snippets_bundle.last_modification_date|datetime_html }}</p>
        {% endif %}

        <!-- Secret bundle warning -->
        {% if not snippets_bundle.public_listing %}
            <p class="text-warning"><i class="fa fa-exclamation-triangle"></i> Ce dossier d'extraits de code n'est pas public. Seules les personnes possédant le lien vers l'extrait peuvent le voir.</p>
        {% endif %}

        <!-- bundle description -->
        <p><i class="fa fa-pencil-square-o"></i> Description :</p>
        <div class="well">
            {{ snippets_bundle.description_html|safe }}
        </div>

        <!-- Staff links -->
        {% if user.is_staff %}
            <p class="text-right"><a href="{% url 'admin:snippets_codesnippet_change' snippet.pk %}"><i class="fa fa-terminal"></i> Modifier l'extrait de code dans l'interface d'administration</a></p>
        {% endif %}

        <!-- Snippets links -->
        <h2><i class="fa fa-code"></i> Extraits de code</h2>

        <!-- Bundle code with download links -->
        <p>Télécharger tous les extraits de code de ce dossier en une seule archive :
            <a href="{{ snippets_bundle.get_download_url }}"><i class="fa fa-file-archive-o"></i> Télécharger {{ snippets_bundle.directory_name }}.zip</a></p>

        <table class="table table-striped table-condensed table-responsive">
            <thead>
            <tr>
                <th>Titre</th>
                <th>Date de création</th>
                <th>Langue</th>
                <th>Licence</th>
                <th>Description</th>
            </tr>
            </thead>

            <tbody>
            {% for snippet in snippets %}
                <tr>
                    <td><a href="{{ snippet.get_absolute_url }}">{{ snippet.title }}</a></td>
                    <td>{{ snippet.creation_date|date_html }}</td>
                    <td>{{ snippet.get_code_language_display }}</td>
                    <td>{% if snippet.license %}<a href="{{ snippet.license.get_absolute_url }}">{{ snippet.license.name }}</a>{% else %}(voir pied de page){% endif %}</td>
                    <td>{{ snippet.description }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5" class="text-center">Aucun extrait de code à afficher <i class="fa fa-frown-o"></i></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/snippets/bundle_list.html
{% extends "snippets/base_bundles.html" %}
{% load accounts tools %}

{% block title %}Dossiers d'extraits de code | {{ block.super }}{% endblock %}

{% block content %}

    <!-- Bundles list -->
    <div class="col-md-12">

        <h1>Dossiers d'extraits de code</h1>
        {# TODO Feeds #}
        <p><a href="{% url "snippets:latest_snippets_rss" %}"><i class="fa fa-rss"></i> Flux RSS des extraits récents</a> (<a href="{% url "snippets:latest_snippets_atom" %}"><i class="fa fa-rss"></i> Flux Atom</a>)</p>

        <!-- Staff links -->
        {% if user.is_staff %}
            <p><a href="{% url 'admin:snippets_codesnippetbundle_add' %}" class="btn btn-primary" role="button"><i class="fa fa-terminal"></i> Ajouter un nouveau dossier d'extraits de code</a></p>
        {% endif %}

        <!-- Bundles -->
        <table class="table table-striped table-condensed table-responsive">
            <thead>
            <tr>
                <th>Titre</th>
                <th>Date de création</th>
                <th>Description</th>
            </tr>
            </thead>

            <tbody>
            {% for bundle in snippets_bundles %}
                <tr>
                    <td><a href="{{ bundle.get_absolute_url }}">{{ bundle.title }}</a></td>
                    <td>{{ bundle.creation_date|date_html }}</td>
                    <td>{{ bundle.description_html|safe }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3" class="text-center">Aucun dossier d'extraits de code à afficher <i class="fa fa-frown-o"></i></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% include "paginator/pagination.html" %}
{% endblock %}

templates/snippets/snippet_detail.html
{% extends "snippets/base_snippets.html" %}
{% load accounts tools %}

{% block breadcrumb %}{{ block.super }}
    <li><a href="{{ snippet.get_absolute_url }}">{{ snippet.title }}</a></li>{% endblock %}

{% block title %}{{ snippet.title }} | {{ block.super }}{% endblock %}

{% block opengraph_title %}{{ snippet.title }}{% endblock %}
{% block opengraph_description %}{{ snippet.description_text|truncatewords:200 }}{% endblock %}
{% block opengraph_image %}{% endblock %}
{% block opengraph_url %}{{ block.super }}{{ snippet.get_absolute_url }}{% endblock %}

{% block head_extra %}
    <style>
        {{ snippet.css_for_display|safe }}
    </style>
{% endblock head_extra %}

{% block content %}

    <!-- Snippet detail -->
    <div class="col-md-12">

        <h1>{{ snippet.title }}</h1>

        <!-- Snippet information -->
        <p><i class="fa fa-user"></i> par {{ snippet.author|user_profile_link }} | <i class="fa fa-calendar"></i> {{ snippet.creation_date|datetime_html }}
        | <i class="fa fa-code"></i> Langue : {{ snippet.get_code_language_display }}
        | <i class="fa fa-copyright"></i> Licence : {% if snippet.license %}<a href="{{ snippet.license.get_absolute_url }}">{{ snippet.license.name }}</a>{% else %}(voir pied de page){% endif %}</p>
        {% if snippet.has_been_modified %}
            <p><i class="fa fa-edit"></i> Modifié pour la derniére fois le {{ snippet.last_modification_date|datetime_html }}</p>
        {% endif %}

        <!-- Secret snippet warning -->
        {% if not snippet.public_listing %}
            <p class="text-warning"><i class="fa fa-exclamation-triangle"></i> Cet extrait de code n'est pas public. Seules les personnes possédant le lien vers l'extrait peuvent le voir.</p>
        {% endif %}

        <!-- Snippet description -->
        <p><i class="fa fa-pencil-square-o"></i> Description :</p>
        <div class="well">
            {{ snippet.description_html|safe }}
        </div>

        <!-- Staff links -->
        {% if user.is_staff %}
            <p class="text-right"><a href="{% url 'admin:snippets_codesnippet_change' snippet.pk %}"><i class="fa fa-terminal"></i> Modifier l'extrait de code dans l'interface d'administration</a></p>
        {% endif %}

        <!-- Snippet code with download and raw source links -->
        <p><i class="fa fa-code"></i> Code source :</p>
        <p><a href="{{ snippet.get_raw_url }}"><i class="fa fa-file-code-o"></i> Voir le code source brut</a>
            | <a href="{{ snippet.get_download_url }}"><i class="fa fa-download"></i> Télécharger {{ snippet.filename }}</a>
            | <a href="{{ snippet.get_zip_download_url }}"><i class="fa fa-file-archive-o"></i> Télécharger {{ snippet.filename }}.zip</a></p>

        <!-- Source code -->
        <div class="codetable">
            {{ snippet.html_for_display|safe }}
        </div>
    </div>
{% endblock %}

templates/snippets/snippet_list.html
{% extends "snippets/base_snippets.html" %}
{% load accounts tools %}

{% block title %}Extraits de code | {{ block.super }}{% endblock %}

{% block content %}

    <!-- Snippets list -->
    <div class="col-md-12">

        <h1>Extraits de code</h1>
        <p><a href="{% url "snippets:latest_snippets_rss" %}"><i class="fa fa-rss"></i> Flux RSS des extraits récents</a> (<a href="{% url "snippets:latest_snippets_atom" %}"><i class="fa fa-rss"></i> Flux Atom</a>)</p>
        <p><a href="{% url "snippets:bundle_index" %}"><i class="fa fa-folder-open-o"></i> Voir la liste des dossiers d'extraits de code disponibles.</a></p>

        <!-- Staff links -->
        {% if user.is_staff %}
            <p><a href="{% url 'admin:snippets_codesnippet_add' %}" class="btn btn-primary" role="button"><i class="fa fa-terminal"></i> Ajouter un nouvel extrait de code</a></p>
        {% endif %}

        <!-- Snippets -->
        <table class="table table-striped table-condensed table-responsive">
            <thead>
            <tr>
                <th>Titre</th>
                <th>Date de création</th>
                <th>Langue</th>
                <th>Licence</th>
                <th>Description</th>
            </tr>
            </thead>

            <tbody>
            {% for snippet in snippets %}
                <tr>
                    <td><a href="{{ snippet.get_absolute_url }}">{{ snippet.title }}</a></td>
                    <td>{{ snippet.creation_date|date_html }}</td>
                    <td>{{ snippet.get_code_language_display }}</td>
                    <td>{% if snippet.license %}<a href="{{ snippet.license.get_absolute_url }}">{{ snippet.license.name }}</a>{% else %}(voir pied de page){% endif %}</td>
                    <td>{{ snippet.description_html|safe }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5" class="text-center">Aucun extrait de code à afficher <i class="fa fa-frown-o"></i></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% include "paginator/pagination.html" %}
{% endblock %}